apiVersion: v1
kind: Secret
metadata:
    name: joplin-postgres-env
    namespace: joplin
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:uPivyxHg,iv:GKj+VjYlcK18ZTmGnV86TJGO8JO0qkksEGraOOU2u7A=,tag:zvwgg/CkDNEfo6ycA5vzkQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:o5tbOcd09z10EKjAqaJYKgtyA3g7mxMzZs3bgRVA7lDG6jLT4G13MVXDmOBvz0oB,iv:T4bq9nb4vZTGqbJz4pXISzZS+EpTgafvHn8dJXtPM4U=,tag:+jrylT0evUiqS+MGKh02ZQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:wA8e9Icz,iv:bl1OMUQkiBMtDs3OFPiAPZNjBwjazNDwhKgM3YbWfm4=,tag:9u69ESHr+VU0r7oGnJNHIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSmRyRDI4bnFFZjhmbEpR
            TmlORzJaME5DYlo3d2tHdlI0UUFqZ0hsdm00CkJXU1pNK09XTmVqWlhiV20vTEpQ
            b2VqZ2RzbUMyc01ibTlpb1ZvWlpCdHcKLS0tIHFndlM1azVCSzJUM2NwRjRUb3Zp
            bFZWdEhWT0t3eHVmcmdNbWN1c09MZVEKpFHC6C6fuKoNg5H2v/fD8IGr2Ia9kWKi
            Pgh1nNuDJuh7TAFNlONYA9ffE9GJGzOWOhahK7llV7GxejHyLWt6Cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T16:31:28Z"
    mac: ENC[AES256_GCM,data:ey8n8dJfcRwhRbsMMNBf+LUFH3/52g8+O4s7hTTU8n9JTTPHzmJi79i+P06aEV5OPQjfbAz3oVSSF9oHNODTRya2kGXLrUcKUx/Silwd1W+sbQoi5XVJU6clG4E75eIOlCSdyfyHle1b+E1WgbImD1S8K/q7Mc7y5+LBumVJnow=,iv:qkWsIzf+Juq8nocffsCnAexqH3bs3lLHkySpI+phvyw=,tag:3dPosKVY9gb5fREiq4gtHA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: joplin-server-env
    namespace: joplin
type: Opaque
stringData:
    APP_BASE_URL: ENC[AES256_GCM,data:Jk7BUHA0BoBLPL/73epe0M9sKxu9JqppdRE1dqE=,iv:C9/mcbx/sbQeqVRTA5yu0Nfwz5K05XiuYX5nBvE+0SA=,tag:XANAg9kiMUnrBwvA7BoAug==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:DHoVy1l8lJsfvNLbh3oc8U9EWPkzt/Y/MU0Ob4wUR1H0XGOMtZsJeg==,iv:wt+bUi0n6fuyzbWp0q4UG+0SDe0rIB0+byY84oBaS+Y=,tag:gSvTRVVfNtS4bD309lblbQ==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:im8xBA==,iv:7cpZs7jdecVrm2CbXJ8m8EefKyDW24+Fjqu48vXpMZw=,tag:Y6HNWNYir7gF7mnabrtfSQ==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:4GNfWtog,iv:vNv0MQBcqmwoPMzZYlYwIOtexo94v6zIrtK8/pnuXg4=,tag:IaHwrPP1cruy9+51+Twgog==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Nn3wqvnL,iv:WA0moQrVM9KtBHd3ZJHSx/hS0v9nF0lDzaFjDByigso=,tag:Gs8j+kvZc5eEIWx5h28ycQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:b5HwrRNHELsvV8WtSY553bSu2ZfISPBcIBbRmrRd5EdOXmxkvcKEIoNH+q21ZS2Y,iv:X/akV67dE9Xfvdhw1tq8Ajsy5+TnGSjnobfV/OIGACg=,tag:6WIvw+9pcAB7VihOz3fgWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSmRyRDI4bnFFZjhmbEpR
            TmlORzJaME5DYlo3d2tHdlI0UUFqZ0hsdm00CkJXU1pNK09XTmVqWlhiV20vTEpQ
            b2VqZ2RzbUMyc01ibTlpb1ZvWlpCdHcKLS0tIHFndlM1azVCSzJUM2NwRjRUb3Zp
            bFZWdEhWT0t3eHVmcmdNbWN1c09MZVEKpFHC6C6fuKoNg5H2v/fD8IGr2Ia9kWKi
            Pgh1nNuDJuh7TAFNlONYA9ffE9GJGzOWOhahK7llV7GxejHyLWt6Cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T16:31:28Z"
    mac: ENC[AES256_GCM,data:ey8n8dJfcRwhRbsMMNBf+LUFH3/52g8+O4s7hTTU8n9JTTPHzmJi79i+P06aEV5OPQjfbAz3oVSSF9oHNODTRya2kGXLrUcKUx/Silwd1W+sbQoi5XVJU6clG4E75eIOlCSdyfyHle1b+E1WgbImD1S8K/q7Mc7y5+LBumVJnow=,iv:qkWsIzf+Juq8nocffsCnAexqH3bs3lLHkySpI+phvyw=,tag:3dPosKVY9gb5fREiq4gtHA==,type:str]
    version: 3.13.3
