apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-container-env
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:l5GF3qVB+pmbLHG5I6R3dJbIlCQ4/rFu5J9aUnc1Gzh1y829yxUUxKCHaBDG4SdnIaSvor2UkMoP85N1aG9h+28u79dridrdv5muXULXyBb7t40p9q1l8zqsgWpVwKAefUPX6Qjq66V4KBgtlz6PajLCpLKOp0bzlg==,iv:hM+QuqNYLd8LVEY1Te7zCXhqKaZ1yERYPW116OTr398=,tag:ZIeu1wF3NWDdFbC7gCQwnA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:K4AfqArrfKQxoME5SbGDTFyQf7JClJod3ktJKIB5Zca8pRWKtJR48PEFl9A=,iv:nDuZG6Lh5i7kARY+4ARJb3V9Ao9TYtKkM3aIiX4RvDU=,tag:UwvO5Xhq1lXVEOc7NvNxBQ==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:d8piORKxcrDVwTHTaPuGXm2p45hxVkl5z7R1xUWpvcGe,iv:2JrYiIHZsrY4u4dWiqzYdt9n1jhhRHAMqkt5lk9L9q8=,tag:ZX6kLkJTFbjqXDL4m1BrLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaTkwakRvSGlrUUtSYVll
            K0pyQWI4YXhPbGFlVmxuMWFjc1pHQVlzYVJRCmNtNFNaaWdGK09LWkNRRmUraXBC
            LzFSaXA5RzlHSnNmcWJVWnhvVTZSM0UKLS0tIGxsUWhGVS9GcDEzYUN1MThGZHYv
            QjF2NXZoYVA5bUFNTU1aZ0tHUmY3dDQKJqrpSYczoUvdD/y5Zyt6ZNrcUWBy3oIi
            Xv5JfLt4HB48Z7w/lexJjr/OzaIiRS9wYIpVUAtKzFBvH3c3AS8YFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T14:09:17Z"
    mac: ENC[AES256_GCM,data:9IR2MEmVUN5niKc1vU03fk70ZuSckRhpvqcAOU/h0EJvPJ6yDw3AxOX2TgDJkLTtIDEoC3EGWgGj5LWS4y1Wpb/iNaTG/21QRM48UJi/ffEXQh21cTMNClLiEgle/XIP5VexBvh4T5nkW4Eidxq0XsnEYIdhNLJ+TQQQ07OCOR4=,iv:gLD4yVY1lFRkURxTUZ4s22jRIuBxFOeWOe1rbF6zHk8=,tag:zhKt/FCaW/rvG+XfwkIrQQ==,type:str]
    version: 3.13.3
