apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-container-env
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:bNkEd7SUrfqwC2Y0z4Xfbe4h7QTW+4sN0/F43JorrdkdjZES6so5DXfEgWXj1MQEDxh1T2aBpu+h3gcSetK2fr8bcZrKWXqcagCcxDb3VYgjOa+zgZMXOWIQJhcY7l1SdhPq5YjANTFYJ3NfUrn4uHfvC3z9n749uwFMkeurcuVbyEoJRuxeZbU=,iv:WQZVvBD+Bcj11bg2jVVdsMUqCKHxEPrI8lqKCZB2JwU=,tag:Q6f8ggejS7Ty/LcB1mhKmg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:oeva6OBah7yapEgO3hy6s3tLuZlnIIHK5RhMbsMa8iyBTWKQ0j56+GAN994=,iv:xY+xszjhdTjquPk69e0NF6t/3uIJPXg28H0ZucTB6oU=,tag:O+18BrwZHpblDeI5/Sffng==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:h+QRiKCn8+a1e5S4oX9YLzXxpL0pOXkvDCkUH98lp26R,iv:qf8XTVwd/vbvgiY8IvFdLNsTw8yi6w1wjicTUB7xLyI=,tag:+NHiBK9UrMmAa59OwIUOJQ==,type:str]
    NEXT_PUBLIC_DISABLE_REGISTRATION: ENC[AES256_GCM,data:i5eFgw==,iv:jztrw+r7qcb2Z2GCeA5H99invKy/g1Nt1Ruf5sJyjzo=,tag:4Y+HpE2VqFVR9m9hjve2VA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYnFyRnU4OEFHSDJ0dUpl
            OFBlbHFsU2RMNGs1WDRyTzBDWnBXRGtYZGhJCkZZdWpzMUFXZjFRR3doNEpZUVpx
            QTk5MWZpMlBBbURHbTJSalhGb0Y3bUEKLS0tIEplYzB1bWhOUCtsbk41ditNNWNZ
            dTd1UnEvelh2VlI1OHgyRHVNN01Fek0KY8Hr8InfeVxvUHvLo8GIAljG8EwBj44o
            wO4nzFDlFNolQwxW36cPL6JA3liwb+hzGnYxyhxtkl14jRTA8+bB+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T14:52:01Z"
    mac: ENC[AES256_GCM,data:g6H6t7QzogXGiMKbxSoViHOtQLd8UxSI4g7celQJaRNLk4h5l6xTfvvXmsqTZJEaaw5lw8R25DCWujMoTP8/XNyS4FTbb2G6yNW6rDtJwCJNvGk+VoncfoBj1r7/zda7ty+SBou7L9jM/7WxsVtT6D5F0z18kPlneKTVNGBsKu0=,iv:SOfTiSSYyx0Efz3xs85iHEJZqSnhzH5TUCw1jymB44Y=,tag:CpUPCwNuY8+3fw8k5otrIA==,type:str]
    version: 3.13.3
