apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-container-env
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:USodGmPKgc2+qS4lHXlaHI9/U6pMYQE9g/zg+C2dvsCL/urwDOHdVbBne0ktKDCrtINQwi/qNM0efmSe98GeEdjk3j9xITjqU84k3FV8sa/dKcnoKmAl4dyz1N/EueAqj8YF9l4CD76E14oE1rY2eoA/Tdb0UoH+5zVZkxc576DxafsNrr4+0/Q=,iv:R7uZM4+VO6TjxnXimuHvPoSpUTzt8qVv4/L7B9kfzs8=,tag:Sf4MwSKDtXhoE2FEhcm1dA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:yKB1fVsRXsDh2eZYXhv4QnHtG3wMGsEuFQXfLkaSsFOGAVKfq4r09sqcpIo=,iv:P1lpc+/PXkn5dB0Pbaz8qHtV+jSbORiAA/R3y2r/fsw=,tag:P4aLmGHZ6vHpKFr0kSda3Q==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:2ErbY/ZLN0MIsjPFEcteZBX0iU277eycCOs5FEHYabOa,iv:Yhk0XdTnuDf1WIjtw6SFU7pM8JboJE4taYi9VW5iNJY=,tag:5E4/YgpE4NcGOaO90qJHmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZXAvaW44TWJQczVibm5U
            bm5vZzdvZzhWaUpTUCtxM0gvb3hIazI2Y3kwCmMvWlpiMERYbUZ3SFBkOUlWdnQ1
            MVhiODRuRi95NnJPc0prSXNnZFZqTm8KLS0tIGc4eW0wcyt5UGM4N0preklWbDlN
            SmdPdGd3YU0xbDl4S3kzcWJlKzNoT3cKf/AWsVdDHY2eG38ipqExC3XdA+cPysIC
            reEFZo11a6ELkwy6Oh+0cng7EF5Ahuq4GqMmv4idDUkV792wmrEsew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T14:27:27Z"
    mac: ENC[AES256_GCM,data:oxjnXk3RwmFxK37jNkT1BmnaDZIMeEuhVjJSPyXZmdwTUrAhcUFokTN0FkCn6FN8fnKCs5I5DOFwfXn1S2E/Cl/usg/5lABdl/PSAPk92sFbxDJJW61VmpjMzv2/euZOesKwRbU067P730H0yysMuWvWiuTj0lk4Gal4++sK/YM=,iv:veYH3Q4oT9cgxBKO+6CxEMh6Qddamrw1rvqp+Bew4ik=,tag:zmqROHjbOjm19MmOd07MFg==,type:str]
    version: 3.13.3
