apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-postgres-env
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:guPUIlHnaoUcHw==,iv:ci/BgGr6ZPQ+old1R6jBnkOn1cTKOjqO9pg6BSGbovo=,tag:jyLzkwjXdS7YcUmOhQ9lMQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:gFWcCNrIZqEN5AgrgzPb1gaBxpU2nJoylHtlozPMrKp5K8WuNsP5z46uMkTmMNJx,iv:Bwak2CZ9BAH6L9plKM+bXfICpOA8bwOvN0TRLx60MRk=,tag:JIIQE4gXDsw8wpE5dX9C5A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:nFK3bZM6faDeDw==,iv:ED58ko0mPsaAQm8k3YlrvwkcAo/dANIyaKehlzXyBrY=,tag:VBqXG1XeIMNmFFNtKZSs1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMK0MvL3hkMXl1SGdyV3Rj
            SDNFVlc0YjdtN2wwcHFwTTNGNm50cncvbkRvClQ1VkI1cXA1U0wvN2ZBUFZLRjVQ
            U3Mrd3J1VlVaYzlZcE44WEVhN01KejgKLS0tIE1qb1lzb2QyOWNmUjdVc21ORTk5
            N1ZXdXBNUWNyWUpWQ3AraDR0c2NRNEEKQTuctAnUS26Y/6MIJNYOCHDtpN+i2yog
            UOQenpU/oGP5IaO3urXSpgCvzTcIb9U31+NjQkckP5Q7n1tv0zbKWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T14:22:42Z"
    mac: ENC[AES256_GCM,data:tJ4LcwdCWcBr3gTqjfRGai7pMezS+o1jY4LfskQBe3ep94O4t9y5WJYts9yvvvIdnaqysVHhO8Fwg/uyD1gDl06u8fJ4tlYyzbni+LvcqAV3+zhTDtoNX1FQnZr5PbS7zLlgt7VOvtie3vz+m6sTr8FO3gA4z7duvCjeaa61IJc=,iv:wAlBiVk5zdKxWy7myjk1KfvYkmywUQp5Yr5w4HgDoxI=,tag:+T1Vb+Jniiw88Cuhpl1fvA==,type:str]
    version: 3.13.3
