apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-postgres-env
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:zgGq8lMuVyIfxw==,iv:2k7BkCmHMxsADiUcqOgHlClfMoD8Kx9Qegt36YmZU6g=,tag:P++Wt8rtJeAUFaM0WJpyRg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:sKrJwFOjmEuu3sugsism32+LMe1R30ypygqv08tZfjc=,iv:n4Zv3OyYW6D+DrwkyxdcCfFKaZi1PvdMpZIzlKOTjOY=,tag:At58Us1CXexS5Cv4DA4FLg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:KqyZfKeXBIPpEQ==,iv:17xm3HwjF7zCxn0mEnjZFVhq2bK/SXVEnkkdBhS9Fx0=,tag:zGCG0JV1q+YufvHTZOMcpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcG01bFAxRmtBdVE1Zzl1
            OXQxbUZEN200dEVrWVV1d2U5akp2YVpHa2k4CmR0cVVZZnN5cTBaNkNvaWE2SGFZ
            S1ZiWGVFQVVvNjFFaFoxZzNMcnJrWjQKLS0tIG5mQ005V0xNSXliU3NKYW16UWlG
            ODJnY2p3Wk9Cam9TNnRIK3BybzZCcUUK2pz5dMPuXFPPwU2FEGyKRJswk1HjmBoI
            P2vRsu3mdGCjDjUXWaYL7Gg/ApZS9Ni5O5FYM+ofbUWSufyCkNHAZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T14:02:27Z"
    mac: ENC[AES256_GCM,data:ddHTipWDqH0F/N7H8wvJ/xQZ3m+iiJZjzFErRVBqRkGuzwVjRo0uhAuZLNahTIrlYRVagoi/FYb+Vx5bD22LdEBoBJHVboHNDhAqoxMVzkguIlqzWkjjb9siSLgU1vt4NtAKZjdzi15QTCY6xO6y7l5G1hMI7M54YMURiMf32AU=,iv:TM3Jh3sdjAX5VIkHdAzUjHmmMv5WsP/A52bRbWucBY0=,tag:8AyaYOtQBUN+RhqLJrsgaw==,type:str]
    version: 3.13.3
