apiVersion: v1
kind: Secret
metadata:
    name: sn-bridge-env
type: Opaque
stringData:
    SN_INSTANCE_URL: ENC[AES256_GCM,data:zCRI5INj9N1J+mQHhOnwCB5/ARgUzAixgkVFKZOeetx8,iv:qeLLFWDmq4CE6KV7axYFqd4o7DA/XAR+WPpG5laKd6k=,tag:LX7vyjM5ui06lCLzfCwjqg==,type:str]
    SN_USERNAME: ENC[AES256_GCM,data:S5YotOA=,iv:x12fBEsOHvU0iGQuj8eM3OKDQIM5IHKlF+W9Nmp5GQE=,tag:jT9IFNmytc1V1PmmSQdUKw==,type:str]
    SN_PASSWORD: ENC[AES256_GCM,data:QQoh0VDUCTdSA17f,iv:v9YXjZ0sTtdpNqONqNBqX0X7F549NKvT4m5d2iYJj+Y=,tag:ZXSHsst6imCrfABFZKCJrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNHkvK2pDclp3eXo1azBa
            UUk4QUM0c3ZmTEZ4UVZGWUNlN2NVZ1FtaGpnCi95WFZFT0RvaDE0dFk1Vy9MSGRY
            MDMvSC9NS0FPN0x0T2VFUXBjYXNtUlEKLS0tIFdsRWI5WjNjd1dXczkzOTA3OXp5
            U3ZYUDVrNmlhRkM1R2x5V3hOZmZOZkkKTSggY6+lstl76Zzu6VQyifKbpj2QyIxi
            jlen9TGhdUQA+Am/aIHlHsKTcdO8k4jTLRa5ulQ0JFzxBTWZoALhPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T11:06:33Z"
    mac: ENC[AES256_GCM,data:RbQ+Bpfdg6Wqm+vUrE1Rujr+OLDQAf1oOEcYkuie7rrsRHRlQjXEa+fjcTVYdH+MKlm5/INjzB9953Rexm4Jm4yiDmjiAI7IjvZmKSavPu5Y/lLNMo5uSpZEbSLrj3ASs97Vm4XiYFd5FzZn/t8b0YNs0HsZw+u5f7G3zCGxe48=,iv:MAtGRwWIv8TqcW96m6mgK0wjBNrVsccHRVPUPWAPDho=,tag:jctoGPwDVTQZFfoS28GHUg==,type:str]
    version: 3.13.3
