apiVersion: v1
kind: Secret
metadata:
    name: sn-bridge-env
type: Opaque
stringData:
    SN_INSTANCE_URL: ENC[AES256_GCM,data:rcb94rQKauoRRUu1LUYMyM0w4xLRdsATcwl7jXYfEXg=,iv:/TyC73b7Mhj1EDPHxWrLJxIcSTXaUFsJxEsPEuimrgQ=,tag:1i5/32HHqDMISj/wvnF6Gw==,type:str]
    SN_USERNAME: ENC[AES256_GCM,data:ylQ4CIYfx54a8nVJWDFr8dBlzhypu3Gx,iv:V8YCzo5d8/Q5IqzbYOh9B+OaUPf6KqlXp5zgqgSC3BE=,tag:b+1K2m4EMjZVdqswjvM+Zw==,type:str]
    SN_PASSWORD: ENC[AES256_GCM,data:CbldVwubQ8IGTw==,iv:qHz4ZhYFOH9SGiJ2pw030ktLUfAjLkZ8OcTAz0Bxx0Y=,tag:h+s5cRkqL7HgRJlEdQ8HbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNHkvK2pDclp3eXo1azBa
            UUk4QUM0c3ZmTEZ4UVZGWUNlN2NVZ1FtaGpnCi95WFZFT0RvaDE0dFk1Vy9MSGRY
            MDMvSC9NS0FPN0x0T2VFUXBjYXNtUlEKLS0tIFdsRWI5WjNjd1dXczkzOTA3OXp5
            U3ZYUDVrNmlhRkM1R2x5V3hOZmZOZkkKTSggY6+lstl76Zzu6VQyifKbpj2QyIxi
            jlen9TGhdUQA+Am/aIHlHsKTcdO8k4jTLRa5ulQ0JFzxBTWZoALhPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T10:17:20Z"
    mac: ENC[AES256_GCM,data:6yxxdU+JClEDh11q8A14o8UXDn3lrT6HgdQPtvGzd5rKIaTXs/lAHq2ucoZyd9ksSLplG/uhCal/z+3Ae5nbz5+r4RS0ZzzsubVgi22RbkHaE3pOLdmqr9Uddfndwamn9utRljkxF1k+hZhHw/HbOu86ZeUuCHfXYjd9/GBl5fQ=,iv:F9SPV9r0jub97dn6kaXWrL3I2zbj8j/U7VKGqiLB3Xc=,tag:20I5arvI+/+T08jWSWQn/w==,type:str]
    version: 3.13.3
