apiVersion: v1
kind: Secret
metadata:
    name: sn-bridge-env
type: Opaque
stringData:
    SN_INSTANCE_URL: ENC[AES256_GCM,data:lYplcE/xTXdiBnaWaCwpfGwf14kAB6UfXTA6RlOc4B9B,iv:/yj9+8Y90ZdcwGtgZh2TyQNiX2OpKz6UwQwkCY1f/WY=,tag:whAbze6Rto/RKZo+8bW0og==,type:str]
    SN_USERNAME: ENC[AES256_GCM,data:O+rcdK4=,iv:nVcOsOOi2Jp/KsdWxPZsFoLOAgCIeRy6FUd+3n642IY=,tag:BRuP5n30+VTDvwaPJhF1TQ==,type:str]
    SN_PASSWORD: ENC[AES256_GCM,data:CQKu4V3MftOSYrt8,iv:HYZfBw//uI5W8RVldULtVIk/lHNNCJCYV0eewbecWek=,tag:FeYm1JbiOC9+MfS9E7R5dA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveGFBdjJ2aWlNK3VxUG1K
            a0oyc0JDaTJBUU04R1VnZmt5cFIvUHFhMHdRCk9oMTMzRzcxSHUxa0dSUTcrL0RX
            bXZuNFlCMFgzMGJyem5DU2JnWFpENFEKLS0tIGRUcFhNRzdKRUtnSXJaSWpndVF0
            TjRSZUtDeDFoNHNQYmNXVFoxd3QvVU0KVisunvTF7FGgtdX0Ymzt5gnZj9+Rp969
            evWvMEWXCUhVC3cBwstHf+OL62I5wPAsG/a5T6baBywBjrI5xBV2CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T11:24:20Z"
    mac: ENC[AES256_GCM,data:LPFi+nRy0/8JqM6rHgyG2xuIOfLbQ/JU7bqPJoxMatO7N0GqXb4DQ/HKQAw4zkXBnqJQZHsCT4pKizqzYT6fiEcOuI0YnPbRvQ3fgLYCIEoGDKaHs/9p7M53FGM5J+lXut+W42vObFD+4tmmhVw5u2RZgFzXcgAycX+bsLNw/w8=,iv:7wNkO+7Y+5QE/a4iSQ5EmwnVPtqlxfFrZYXiro4pmGk=,tag:96P0b7XKBDZTJyQwK4Wh0Q==,type:str]
    version: 3.13.3
