apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:rieH2vjhHS/PBSxrt6VmQCOGBoupDXPWVbuiJ1A5ugYLEJZulMCeKiqv04pELDb4CibiyszbawJ17F4z50deoIoPaGx4uS0BgnF37ihU8aJdXKDE+wKtB+bQe3oC3Y076GxmNcPw6LY2CXLMrpkPTsdvP7aR66Wi+Ifn6ROOMy5DsOeYNEWUbmrdaiRmD9fm8PcIUGHW26qYRoTmWn6RJUJam5PxAeSLk1Pak8Nj1Kvu0rdChlBW17TccJwUevsgyfXJ1SpvLy06bv8zoxgipokbAhMKxGwN2Arrdccux7VoPpeBgUQwoZiZrkc=,iv:qknUBB1qeV+Rk2SN9C7fyQYs2w9YleHsbCVOLknRJgc=,tag:mTDXESwN4+J77BYUxH4Cag==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdG42SUdqcWJPeTFzNFoz
            TVlqZktZTGdtNWhEUTJVdWFaZXVSUDBocFNnCjhlaWdnZHRHRXZFdlZieWlOTmRZ
            QmFkTFNGaVhmVm1qK3EwMTdLQWt3R3cKLS0tIHJST0wxTlRORmc0RTk5T0lsdk5n
            UWtrb1Vod3hDZGg0VTJSeVlHVVlLb3cKtJCad+BdglzeZb8P10ZOgi3iR6xyJSG2
            0gQXvABvVpFl+OslZlRXtJ8QQpd86Q4u4RH/M85vP1cInI4aiUaNfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T08:00:35Z"
    mac: ENC[AES256_GCM,data:2Cbag7CkFTlniGolUjFL/3qVvnHGLArFVtQKp6UT2nk3D4gmuJN/CYIgyanNVlVz/JiVgWSO13njMKBuWND3e4U9D4sU15WcdCuRNyTo4zBpx7hhuWJmZ5u/5nzzIK1Df8OhPtHZ6ALm/BjK3kpnet0kYE6xEW1fEsgybN4as0M=,iv:4g7gfCWow++hsqR7gabqnZht5Z4vxTrjLDhGmx/tpBk=,tag:4DXWNh6EIX+xU6DpzVhhIQ==,type:str]
    version: 3.13.3
