apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:shYvMKgg25xU9JUBb+QaurvhYwWloc/XcEi5XIps8sCvNp+Rj2WZFt/q8i6UYJv4RV4Dd5LRUQvpB9X92/YT7w==,iv:7fOn3RrQ+Ww8ggQtMUPomurlLskrN6VVAR5vAOMgwew=,tag:Qqhg+GGALRjXQcX3jiR91A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MWdBZktKQkVrQzE2SUlQ
            VVlCUnNDdFpGeVhmOTFadDF0VXRkMHRxS0JRCnh1TzN3VkR5VTBGVENqODIyTndT
            TzBGbGZNWHZld1hqU3doNDcySHlWaHMKLS0tIE8xZzRhbWFnZ2J5K0lsUGZzYXli
            eUsxS0hVclN1d25yVVdYNzBmbHNUQVUKipb3+Qn0ye1RdQBSlIarblNaNzMb2Ckp
            rUB8NeY2LACYe+Nf5xEzZY9KDRcUZFu3ElpOapPxfpRxHFtUYhSScw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T03:59:04Z"
    mac: ENC[AES256_GCM,data:xDR57+FingXXyVJPxgdgrsbK4kZERpjIi/bGGpYAs6bbO24m1y/xE+OGbSIQz3ikMUHC24mkE7agPMiuWCwItnAqOH3yiiFSYSOAtSCzNUlEx0gvmPrhPtBqFJMJ+98Jd76Dw1yYW3k28RU5/5v7z6HIyTkUA7cC+yTGm0HWmHU=,iv:oI+udS+wZYAQ4dj16lwdRo4okbZOZ89DTMap+3jN8PA=,tag:VtIYkANktLgmxDt9jU0hrQ==,type:str]
    version: 3.13.3
