apiVersion: v1
kind: Secret
metadata:
    name: homepage-container-env
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:N2fLJ+fhOPeLOonOVWHQ2ompXqxWpLBjmxcNhOum55M=,iv:xPohhButOMYegfY3smIuznAxtI78Mm5xcmvGbtiufUw=,tag:gds2iF3lBWi8MPZH2A9zsQ==,type:str]
    HOMEPAGE_VAR_NAVIDROME_USER: ENC[AES256_GCM,data:rW4a2GM=,iv:Q26tvsOqBIL1C95TXaT3iy43E+eY3TtuCkNMPOvwcWg=,tag:+Fgl14sGy0aMBDexRj736w==,type:str]
    HOMEPAGE_VAR_NAVIDROME_TOKEN: ENC[AES256_GCM,data:gH/3CcOoV6zxOrpBLZRcVYrqpTzdRfOdApROTT+a4R4=,iv:9nQL9JKzTyhg5nY9EQFNI01TpIDZB1yjvOKiazYwSZ4=,tag:yOvMVNd0VfU201QxEbbtcg==,type:str]
    HOMEPAGE_VAR_NAVIDROME_SALT: ENC[AES256_GCM,data:koZA2tZoniBnm/1H9Q92+P9MY0DV6UTNbyKcVJsMEM4=,iv:KWVm+m1GqY7SJfrTOOm3jTZNhTcCxLKW0Tq0MZuwL40=,tag:0/C4qX1MsU8/SIktzErkBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTldRTFJ6c2lzdisxMk11
            dlh5U1pvanlGR3pROVE5Y09UaFBydlMwNUF3Cndzc3pjaVp1c21yT0xNcXovNE1P
            aXdIZWlaTWVxZFIyYzdZdFBVemtHeHcKLS0tIFloNnNsSURZaUlFa2c5clJ2eEIw
            Y3MxZUlic0FydEVROTJvNUlSWDVLcmcKwD1yUB8vhjmKC7zXROFW5TUcOtGdBV6B
            RsYJgTtkAQ1HAEBwOhg0E736DE4Df1EIuMy4oILGfYzMcQtNmn2ovg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T10:32:14Z"
    mac: ENC[AES256_GCM,data:oe7+4n7RE2sx1SSayT66uimuKPNdhL4h7/CloLlxCpIYi8PRUjQX+DRh2CigIPq0pGqOii0WNsnJqT6D5/F9KRFmqBUzl9evT6cpiKlR5mjj9OcEu1Bv1n3UtlgjJxhAZrY204wVp4qiHai/fHvoB0ycyX3gXFkI6vRE+g1C+2w=,iv:lBsjnP0nZDKfQb9hQfQz46wAGpRPb7m8lEhMzx9fZp4=,tag:HO6tIPiK3FHtA5MH4j8vGQ==,type:str]
    version: 3.13.3
