apiVersion: v1
kind: Secret
metadata:
    name: homepage-container-env
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:N2fLJ+fhOPeLOonOVWHQ2ompXqxWpLBjmxcNhOum55M=,iv:xPohhButOMYegfY3smIuznAxtI78Mm5xcmvGbtiufUw=,tag:gds2iF3lBWi8MPZH2A9zsQ==,type:str]
    HOMEPAGE_VAR_NAVIDROME_USER: ENC[AES256_GCM,data:rW4a2GM=,iv:Q26tvsOqBIL1C95TXaT3iy43E+eY3TtuCkNMPOvwcWg=,tag:+Fgl14sGy0aMBDexRj736w==,type:str]
    HOMEPAGE_VAR_NAVIDROME_TOKEN: ENC[AES256_GCM,data:NG7+arbbojyeUgThFiAO33uH5ynttOwT3Q2CnRSHfQ8=,iv:sWrl1TLZCVQeHreDe14L3EEvxUWr9+jVXYOasBMUSZA=,tag:8kk7dhml+bnl8xQ9Z+eijQ==,type:str]
    HOMEPAGE_VAR_NAVIDROME_SALT: ENC[AES256_GCM,data:sNNp37ik2UlZ,iv:1Drnd5F6/T7sp/y7g8FYK8C7KVUtDGtr6EVszj+7ssQ=,tag:aHW3kk0ysfJSx6REHAb78A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTldRTFJ6c2lzdisxMk11
            dlh5U1pvanlGR3pROVE5Y09UaFBydlMwNUF3Cndzc3pjaVp1c21yT0xNcXovNE1P
            aXdIZWlaTWVxZFIyYzdZdFBVemtHeHcKLS0tIFloNnNsSURZaUlFa2c5clJ2eEIw
            Y3MxZUlic0FydEVROTJvNUlSWDVLcmcKwD1yUB8vhjmKC7zXROFW5TUcOtGdBV6B
            RsYJgTtkAQ1HAEBwOhg0E736DE4Df1EIuMy4oILGfYzMcQtNmn2ovg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T07:38:47Z"
    mac: ENC[AES256_GCM,data:FTkK/5X62lJdwbJOF6nKJK/ey7GszyIpNSIFFFsWOZy3TsrIE6216dx2qXYlCML16nKd3Zv+Jvt7xe2RPBzZS+yIipjSfnz3UynWIivavK3TAh0a8to0PfaCIUV2TrlEk/elflXbMiZfoO02ZUjzxjP8vn6fVM3Evg5iQDaCGXM=,iv:XwOCvtOpRShM3ZgYWJovRr6hhnRET5qEv7j5lOb+O7g=,tag:e+rT6JifzwJFxpx4viTpng==,type:str]
    version: 3.13.3
