apiVersion: v1
kind: Secret
metadata:
    name: homepage-container-env
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:DsbcEZEzNxUgNBaZ2IM8lNkPE0cOZ1fcvYMVKvAYYCc=,iv:zkCYN1NmEOejxDYgWyVa3YtCrbn3ue09e3BYPnawIuA=,tag:cu2sTtGo8OGDbkb4kNK4cA==,type:str]
    HOMEPAGE_VAR_NAVIDROME_USER: ENC[AES256_GCM,data:Swtz8kM=,iv:MItHzuu1JkVsEoJj0oH/dKrY9T5YZKU3y/0rLaaFaDo=,tag:aSHN670lanLY25AKYM186g==,type:str]
    HOMEPAGE_VAR_NAVIDROME_TOKEN: ENC[AES256_GCM,data:OqtU1F4BZC58kPDtHoAZaVAN/h/4LfkMrEwXq8wnWlQ=,iv:g53BK9cr+9nwXwGnBfLDXAAXNCbBdZiB+xp2g5/30pA=,tag:QSA/dsLLBG2vQH19EgDNNA==,type:str]
    HOMEPAGE_VAR_NAVIDROME_SALT: ENC[AES256_GCM,data:F2nIpNuLLgn8037EeZ4aaHYe5D8rWjmcRMS4dtO2Drg=,iv:My//cujGQIw3XquqevbGjJvPpX5/jqJKUDpbFDdcqek=,tag:VCrLdL1sdZ0TYZ974k3aGg==,type:str]
    HOMEPAGE_VAR_SPARKYFITNESS_KEY: ENC[AES256_GCM,data:9qoWCzFWvhUgRytktH2YNLa8HcU6dddasSdKp0qYybIoYWj+LWkyEoToS0Fho0C5CjYao3JUND4VOZ9FJU680w==,iv:yGIwM7alTzoyQCbKDXjt2YOKg6AlUQ8XI9+zBhVchm8=,tag:WnkbPIyDtCUDG+fCPiyshw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYzZKaEE0SmdldktkSVRG
            NXFuSHBIcm9RTmhkTk1YS01TcVZXMUg5RURzCmdMaXQxbkNOaWlwZkI0NHJJTnlu
            RE1jTUxuSXdYUDdaWitFN3dUNkVrRVkKLS0tIFpXRWgzUjJTZGJId2xVYWx4cHYy
            ZlMxMlhxb3RiUnN5d2Zhd0hGMkRsQ00KmqlmASC/CSEhw2QEO2E1+3KBqWZu/AxV
            OFO8iBKf/VCeGxPFt4leppmRxzBCKnUk5FAnEmT8WcqIOqPObB6xMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T04:11:25Z"
    mac: ENC[AES256_GCM,data:CVLQ1e5/6rklBpMlwUR03SggSM/O+IrG8+8LoVAFgZr7IBT51CfaWV1ZJE+YKMeBmBpUg1jywgb0Jbbl9k5o9Ktj6zWADdLiX1RnET50PxF0X3KDXtCB24G4/IkNbG+fBGq5yWpJcPgPO6EkVIIJAi37HmR4smvNl0yig+fRaOo=,iv:JSou6W71y8hu8nbGuQKn3bE8ukzVAuiuPZKgqLqytG0=,tag:x2N1uhP4piUIVbsZOm9ogw==,type:str]
    version: 3.13.3
