apiVersion: v1
kind: Secret
metadata:
    name: homepage-container-env
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: acdd7e3b538e4dbfa639a2c73cf0eb8c
    HOMEPAGE_VAR_NAVIDROME_USER: tonyg
    HOMEPAGE_VAR_NAVIDROME_TOKEN: 0534250b8f1e8ab9cf1f875743f0be86
    HOMEPAGE_VAR_NAVIDROME_SALT: 0a4e35966476eb367abd898e2b4258a6
    HOMEPAGE_VAR_SPARKYFITNESS_KEY: RmTLIQRNPAoYhFuNgHqgWspSWEDbbHNMZpOrOYlsQHYgobuNRlrLxEUroKcVpxjV
