apiVersion: v1
data:
    password: ENC[AES256_GCM,data:2FCw7O6s3Tc=,iv:IaAFcjX9Vk1fFD41VkLuWtNI+Hs71dCOAFRlHpmgwVU=,tag:jO6BgUqve4zTuPyFkUzgBQ==,type:str]
    user: ENC[AES256_GCM,data:ZgqJSKOibZI=,iv:xF7VoMcCvMRHtpBnjW7wqOlgTts0DQ0kzePMQWZ3/pM=,tag:oPgMvb373Dsufvj4xpsACg==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcEp2UEIzRUNTcGdvV3R5
            NEZ0aktCNjFzYVZpbWFvZXNiekdoSzVyRWlZCk1FOC9lODcxRDhwT2h1WHRqd1hG
            UUFrYkJuMVprMy81bUVha3FneUhUcDgKLS0tIFZWdi9wd3pnU2NSSkFhUjVXc2JS
            dTdJKzZVa0FtYklZQlBhbkRoOUZxdVkKeH7drxhjc/qxJKnAjEiW1KN3UG5Hm/u/
            Xs5gKaP14xTwhGqCbfNsDqjRtn8WW+e7zBvClENFcUQNRfd2Enmvhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qslrqkngwjzvh9kg0vf0ccy70fk6m68plem26225pnkklxar7p4swpchnh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T06:34:02Z"
    mac: ENC[AES256_GCM,data:t+maXGq60CV5qsfCTSM0La07RnZDTqEqFQFYrNx6nNp+56baSvo7rdgGcf9/W0WfX+PCJtxyMn8s/qFbTohx2VficFl0Ak9tAFd5A7e/S3CVczUbeiVDCBDXnAp1hdjgo1g/QsOV9W2S+Q5ekHGBGA7KbmCyvHmeE2ZG+Xsptvg=,iv:44KNIWqSvUOgsIceE5U+MGJtt4ph7NIWh8VUtTe1Gsc=,tag:XkhvB197TIutvn3cGc3c/A==,type:str]
    version: 3.13.3
