apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zennotes-config
  namespace: zennotes
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zennotes-vault
  namespace: zennotes
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi