apiVersion: v1
kind: Secret
metadata:
    name: zennotes-auth
type: Opaque
stringData:
    ZENNOTES_AUTH_TOKEN: ENC[AES256_GCM,data:PdDuaryHY+0EBh2I5Hey3Mu4LqYmGmOtXNgWkXPVxpDfCi3yaQFfQlAFSHUjol51A+4rvjaY9EcA6SyCZyJ7xQ==,iv:gvXvKjYHaoiBNcCHZtB2iBNZQpVi7p1EDKZcWzZuwgs=,tag:fXsRi10BjfYE5LlVf4Ac0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRd3d6Uk5WaTVHVHI0clkw
            ckcwK0tDR2dsS2E3N2hvWFJycUN0aWZNZ2kwCkpLOWRvc0M0SGt5SU1adnRONEF5
            eU5ud0FVNDkzNTV2cmx3U1d5cUdKZW8KLS0tIGZFWFpKRlBJdXJZbWQxSzlXY0Jv
            R3FYYmowcXNFeGp2VUM2c1E0clRGRFEK69frXEocZSgMKkF3ot+l7x2IQDkQ0GmU
            oquAZ27SFNKstOM3G+EbAOUjL6onPE0MT83gvv4HlLcmIgzU1TvQ2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T09:08:42Z"
    mac: ENC[AES256_GCM,data:wzbu6wpENbZboeD6HcpiLO4Jw8hjPuCx59PTNRcclzuJz70lTRhK5yb+4A+X9NVNRgkgKlXatdesSpVJ3AJG77kktU+CFvhLWxBS6xYGwgvwJNc2XXruuAvl9sKiALH/3+wzaI60l8gOn+DbSeROWKcAMrLzhGoVqhHBVY/HU9g=,iv:mF9lE/OVOENEBzjsGavelKLkjYvMOGIgcOy6LQp1OxY=,tag:8onqep9lEV4kni37Nbu+qg==,type:str]
    version: 3.13.3
