apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkyfitness-app
  namespace: sparkyfitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkyfitness-app
  template:
    metadata:
      labels:
        app: sparkyfitness-app
    spec:
      containers:
        - name: sparkyfitness
          image: codewithcj/sparkyfitness:v1.6.1
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: sparkyfitness-secrets
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10