apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkyfitness-db
  namespace: sparkyfitness
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sparkyfitness-db
  template:
    metadata:
      labels:
        app: sparkyfitness-db
    spec:
      containers:
        - name: postgres
          image: postgres:15.8-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: sparkyfitness-secrets
          env:
            - name: POSTGRES_DB
              value: sparkyfitness
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: sparkyfitness-db-data