apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-secrets
    namespace: sparkyfitness
type: Opaque
stringData:
    SPARKY_FITNESS_DB_USER: ENC[AES256_GCM,data:SXs+fRFCxPM=,iv:RyzcUqTLOIcPPP1ZPBlkg5UVc5OmKEoh1bKTh6xp08s=,tag:OGboFgBvYJpJ1zzB69REdg==,type:str]
    SPARKY_FITNESS_DB_PASSWORD: ENC[AES256_GCM,data:xCNY1d1HyWDJYtR6rcrXFbI9i4wplDgyW6KUap3mV4s=,iv:CpJ51xku/xRbQ1Cv8motBq+DN3w2s1urM7NI7T7YqJY=,tag:dF7WtDdkLA27e5r9uJSYyQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:G8s5O6tZs6Y=,iv:mDLOE1qcufXvuW+bKYZ+lVjnogSA8Y8F63pBEDdLiPQ=,tag:/DuxI0GAgjiM4nBEbZvZrw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XTW4dZvN93dlIjYTIFb6khPeYHTSDbIlWL0slYEBMGY=,iv:7bxylEir//5D/z6ExIPC7Y2gl8cqEToJN3+S+YthkV8=,tag:+pCdiwWYM6wpOkiusC3Fig==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:b0LWk9mqc1DjTbRMdQ==,iv:JmdcQJO3GgCN1SMsjQiR1OLO/xW9t3nfndpwa1k6lVA=,tag:yBqtjfTdj18GziSwn+0KbQ==,type:str]
    SPARKY_FITNESS_APP_DB_USER: ENC[AES256_GCM,data:WkNLGcv4M1uE,iv:L/Otz6+oNw/zHVwv+lrmePLuiHYIL/txcuTghM4RCVA=,tag:Mp+ITatHGmhlbhPxomYoug==,type:str]
    SPARKY_FITNESS_APP_DB_PASSWORD: ENC[AES256_GCM,data:vRRYoIKvKtnntmdbWCsidxxYaUOMX3nthjLQ8d1y23A=,iv:4NpCzrjKBI5ZYvJep/3sGeLyX6G49EFXvKpP7/UGCBw=,tag:NldCfa5G+xgHEANku1Efxw==,type:str]
    SPARKY_FITNESS_FRONTEND_URL: ENC[AES256_GCM,data:4QIgOA9UP2GwOE8c+IBhHnrokdTFAiZHn9z/LM1C,iv:lE6j++58i8lDTDxsF6XGmB2/cinvcPLuU71cikFJrTI=,tag:XWQyp0f5+x2P2IKcEq5koQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:I+ocU4N/ETC4mTWaj8saEkqrvvD61K61phJims17wijZNaZc03B5bHGojBM=,iv:lUhjt1dv9M/aTvkuUmgucVz5V6Zh90qpqOF8cJFFY1c=,tag:cMN/56/S1ck/RsnDkli61A==,type:str]
    SPARKY_FITNESS_API_ENCRYPTION_KEY: ENC[AES256_GCM,data:AUGrKGE5JXz5D5BY/JN6wno/kVOa6WGWrYRrWwDH4eIZ7gedF67cnqgZLMI=,iv:kWsFPECZ14z9BkCxd0IS6NL8fAlFeL9ZGkXOja8Zct8=,tag:XM5JSRl0/Q5BsNIP4bIhGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRE9iVlpJRzBvZHErT3NN
            NmpvMFJKS0dtSk1RbEg3OHpvMTFkWU9ZdUNZCkM5emtKUzJoMFhQb2E2dTl3cGhp
            R2VFSlM1azZ6SUIzem4rNFkwcVgzajAKLS0tIERTWjlvNmthVzJFN3MwTU5FT3hw
            QlZrNjBjeUh1dUUyTHMrZEdFRjlJSUUK1H3kMDEtg6l1VKH5YNuutfT4y3u/sPeY
            qkqC2tkCcrSMDe15L4plY/0KdTUTVMUJwE3rC1NM0vJBEvlPm2fBjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T19:57:36Z"
    mac: ENC[AES256_GCM,data:CdFExmO9rj6FfXwnTMMUwwzDlBEz42eN3TP2a7hb8fQie+Ff2mKUvYJmGhRMynWs2vkoVUCnX3PAV4vyXiNAxlWJaRuqlWL4QJKDrNk6XZV8KFUGz8/k9FnZu5GcPn4Srlk1DEOM6RYfpWFyBnan5wuUi94Mvl6ZUBXANznyatM=,iv:bZtNaQXosVpFDr37hMEtys5qUtrMKljH3tXY6rIhaKM=,tag:xQ77iMMQhqSw/gl3gL7hjw==,type:str]
    version: 3.13.3
