apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-secrets
    namespace: sparkyfitness
type: Opaque
stringData:
    SPARKY_FITNESS_DB_PASSWORD: ENC[AES256_GCM,data:LUtPPnNDJXWrl52TYMuUIcsZF/0VDTepYbkppz9hsNo=,iv:I2HFz+ncGsQM5NHJBVqX2ZZNqBg/MnmT6/LzDG2Rs0A=,tag:R/pyT74QljhlXYz14Sln+w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:4befNyQQPRA=,iv:gVHiRMMb7B+1+vibBohGJBOUXzaEwJ1UXk8UwgeT270=,tag:hVhINwHjL+0UQzC6ZGb8yQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:TwJKE54KmM6FpxNaN1OrtbQ4IvVmD5telrmzHX3Moew=,iv:+8PEv5BCnMxCxwgCy3JhGktP2OABNiMARVefeIrK/6s=,tag:+OVj/duwvO2GrMlx9tEuDA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:tgRfsg8zFlJXd2Z57Q==,iv:HKCvb78Ei+OLCdBAB9oy6eCZwaEl1jJeSHqLd8eDVvU=,tag:z9DA7O0drC/7xlDn7wM8MA==,type:str]
    SPARKY_FITNESS_APP_DB_USER: ENC[AES256_GCM,data:/Y++tAxlkTBv,iv:TgePy/Klnxiv3maEVLfdnSF1YISWAholeotv5mgZTZY=,tag:prB4L3wadODY0CsWTRMIQQ==,type:str]
    SPARKY_FITNESS_APP_DB_PASSWORD: ENC[AES256_GCM,data:hwLse769PoKQLDm+V0XBaOsdbmQfQX5vsGa7JjIyClk=,iv:l3g7w2Rs0ai7c5Sn/kL2Usv+8Pa8wahmu66/tOodnNY=,tag:d1MeDnF2vUjwVyBAw/K5AA==,type:str]
    SPARKY_FITNESS_FRONTEND_URL: ENC[AES256_GCM,data:lRedGv0/zK1ay9KNkUmagIkjmq4tPhOHE1DZqnm0,iv:W2Gm+K3fyEGSarWVCIbqOxj5BZRsceDLCRW1HIb2Bio=,tag:LlyURTUfhYwxL+kYl00FaA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:kCXztC05m9Rf1qzGl2dPkfoDrdubynsyl+kdKef01+4JSCuJp2jdLXKhFL8=,iv:Mh8dtvncN9fLOPE+P2xqQniJrx+qrqsOlfQDktV12Eo=,tag:Hdg1nsz/i+bOZEO93wDvkg==,type:str]
    SPARKY_FITNESS_API_ENCRYPTION_KEY: ENC[AES256_GCM,data:ajHeurQ3P0xQmAMwayBegMbf5BGXbgq42i3GSu0nFREaW1B8LeU8GBJFlUg=,iv:s5YFtLJ5Kw3lIjqSVk9M+Y1WrhSMS50Y1BA3WT/FV/M=,tag:ASGcHFdEus9e82VFtKlnmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZVNzZHJpTmRtN2dkRE1h
            am95ZEc4aUtkdXpMSzNPUjJLOTYvUWQxZUhvCmxKa1lzeCtVR1d2RmI0WWZXQXp3
            TE1OTW9TeDIrMHlnUWVYY3ZrbGVXYkEKLS0tIDlWNzVPQm8rL0MxNGdEc0FyRTlz
            RDBSQkp2MklEOU52ZHpsWVhnRjRTRHcKhRZRghDIf+C03bFH71da8NvO4SZnDrW2
            i9SUztbTS4c8P6ODugWRisO2KiKZ59ov/q3DyJ6Tf84f0f8j2U4G7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T19:17:13Z"
    mac: ENC[AES256_GCM,data:KOcRZ3S8/5/6ZXGaa/mMVB8E2tkHx3JSszxP03BBm3s2wFLq6MH+pjajbIE8LPsBc5dIMbkMS8iba+xtunOnT+V8t3g1A+u102aXZqsgOZKjRpNID3NvBmMUhq/XBDJjGdeZVnHYDBW7OsqiM/Jx2SSjgMxKh1WkEvcAKhVysbQ=,iv:fB76VJq3UpAbRZmhPDACYlU/HvikO6UibAQpyOdDxSg=,tag:9GJ6l+qxBDo8ZkYnIZkNVA==,type:str]
    version: 3.13.3
