apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkyfitness-server
  namespace: sparkyfitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkyfitness-server
  template:
    metadata:
      labels:
        app: sparkyfitness-server
    spec:
      containers:
        - name: sparkyfitness-server
          image: codewithcj/sparkyfitness_server:v1.6.1
          ports:
            - containerPort: 3010
          envFrom:
            - secretRef:
                name: sparkyfitness-secrets
          env:
            - name: SPARKY_FITNESS_DB_HOST
              value: sparkyfitness-db
            - name: SPARKY_FITNESS_DB_PORT
              value: "5432"
            - name: SPARKY_FITNESS_DB_NAME
              value: sparkyfitness
          readinessProbe:
            httpGet:
              path: /
              port: 3010
            initialDelaySeconds: 10
            periodSeconds: 10