apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
        - name: freshrss
          image: freshrss/freshrss:1.29.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: freshrss-data
              mountPath: /var/www/FreshRSS/data
      volumes:
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-data-pvc