apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: full
            widgets:
              - type: monitor
                title: Services
                cache: 1m
                sites:
                  - title: Navidrome
                    url: https://navidrome.tonygunnca.com
                    check-url: http://navidrome.navidrome.svc.cluster.local:4533
                    icon: si:navidrome
                  - title: Nextcloud
                    url: https://nextcloud.tonygunnca.com
                    icon: si:nextcloud
                  - title: Vaultwarden
                    url: https://vault.tonygunnca.com
                    check-url: http://vaultwarden.vaultwarden.svc.cluster.local:80
                    icon: si:vaultwarden
                  - title: Linkding
                    url: https://linkding.tonygunnca.com
                    check-url: http://linkding.linkding.svc.cluster.local:9090
                    icon: si:linkding
              - type: server-stats
                servers:
                  - type: local
                    name: pi-cluster
                  - type: custom-api
  title: Next Race
  cache: 2h
  url: https://f1api.dev/api/current/next
  template: |
    <div class="flex flex-column gap-10">
      {{ $session := index (.JSON.Array "race") 0 }}
      <p class="size-h5">
        Round {{ .JSON.Int "round" }}
      </p>

      <div class="margin-block-4">
        <p class="color-highlight">{{ $session.String "raceName" }}</p>
        <p class="color-primary">
          <span>Race</span>
          {{ $datetime := concat ($session.String "schedule.race.date") "T" ($session.String "schedule.race.time") }}
          <span
            class="color-highlight"
            title="{{ $session.String "schedule.race.date" }}"
            {{ parseRelativeTime "rfc3339" $datetime }}
          ></span>
        </p>
        <p class="size-h5">{{ $session.String "schedule.race.date" }} at {{ $session.String "schedule.race.time" }}</p>
      </div>

      <ul class="size-h5 attachments">
        <li>{{ $session.String "circuit.country" }}</li>
        <li>{{ $session.String "circuit.city" }}</li>
        <li>{{ $session.String "circuit.circuitName" }}</li>
      </ul>
    </div>
          - size: small
            widgets:
              - type: weather
                location: Los Angeles, United States
              - type: clock
                hour-format: 24h