apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: full
            widgets:
              - type: monitor
                title: Services
                cache: 1m
                sites:
                  - title: Navidrome
                    url: https://navidrome.tonygunnca.com
                    check-url: http://navidrome.navidrome.svc.cluster.local:4533
                    icon: si:navidrome
                  - title: Nextcloud
                    url: https://nextcloud.tonygunnca.com
                    icon: si:nextcloud
                  - title: Vaultwarden
                    url: https://vault.tonygunnca.com
                    check-url: http://vaultwarden.vaultwarden.svc.cluster.local:80
                    icon: si:vaultwarden
                  - title: Linkding
                    url: https://linkding.tonygunnca.com
                    check-url: http://linkding.linkding.svc.cluster.local:9090
                    icon: si:linkding
                  - title: Jellyfin
                    url: https://jellyfin.tonygunnca.com
                    check-url: http://jellyfin.jellyfin.svc.cluster.local:8096
                    icon: si:jellyfin
              - type: server-stats
                servers:
                  - type: local
                    name: pi-cluster
          - size: small
            widgets:
              - type: weather
                location: Los Angeles, United States
              - type: clock
                hour-format: 24h