apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: full
            widgets:
              - type: monitor
                title: Services
                sites:
                  - title: Navidrome
                    url: https://navidrome.tonygunnca.com
                  - title: Nextcloud
                    url: https://nextcloud.tonygunnca.com
                  - title: Vaultwarden
                    url: https://vaultwarden.tonygunnca.com
                  - title: Linkding
                    url: https://linkding.tonygunnca.com
                  - title: Grafana
                    url: https://grafana.tonygunnca.com
              - type: server-stats
                servers:
                  - type: local
                    name: pi-cluster
          - size: small
            widgets:
              - type: weather
                location: your city, your country
              - type: clock
                hour-format: 24h