apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7LKyrNDfya0HIq1Od8AYb0dGr/671emb,iv:aJvm7k6RZcGU0Vtb6nWsETKNW03sdBqCj/Yzua9rL6s=,tag:L7DMRicYftscYin3orVI6Q==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:8gcjevVl0vt4RVI9HldGoT/uvclAo/VM,iv:8wMAiOJEYa98pT3YjqV9BU8gmCz2b91Rr1+GGTISHkA=,tag:6BH9fVEp/N4NpbsNe90pzA==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:OBmf0SAJP00=,iv:0q3Zd5Dc6KksToqgNT9YUjdeNf8WmPgmJg+gSmAwZ+U=,tag:+3fLitnat4/14fyIZaJGtw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:vi4kDVTGkyapxwwK3oO2L/6HrJrcH7YP,iv:L3PzfPclOx5FSgXqPz3gHpMJpHixffHSzGRKW5gJdSw=,tag:ZXW4PxROvFyUzDXxgn3V7A==,type:str]
kind: Secret
metadata:
    name: nextcloud-container-env
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSWJRZTJXTURaREdGcU05
            Rk5BVjdiU2lkRnpxczJGQ1NmaENXQ1hXK3dzCmJzRkk2d2ZiNmF4bWM1Z2h4WkFl
            MExYVEloRWNZWVFKelFGS29VK1AwczgKLS0tIFIrajVTVEUvR0tUeXRvSEhoM3U3
            dVF3dWpWUEFPSE50YkdVa1czcnpnY0kKD8dwc5lPX0NkXMK2KVujJOR7I8HufHx6
            UxxFqr4BUFVoFWiEkKUdRG1J27laPmtievtNAuGjgU5Rtxpc1iBgYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T09:02:00Z"
    mac: ENC[AES256_GCM,data:19aEjNnXMXcsdJ14zP7/84AlQqrg/LpU8/2AJr+4BMHNPyM5sg/k9qTzSjSXRPt/+TozQs0YIo/x53h8Umj9fjRKwtXaNlm6WjCHtgP814be6x0DGL/ZSYTmg4Zg8YIK1t6Dh2hD4hCByjZu/NSxP6JWRQ6U+mHlNUIoHMRXKfA=,iv:KeEUvfQAtgt/JJAHEWukBKbHCqXWKJpKundCgnHpq64=,tag:WOJxy3o3LhLoMDYMGPD2fA==,type:str]
    version: 3.13.3
