apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KJXuirIBd9ggVDvHIspoDg+Nie1QrgfH,iv:Zo60FchdAmK3pu+nrgOWGKWH4fP5TL5Yfp9OWT6vAVY=,tag:tzh5mk/mca45c20rGc0Hbw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:711AT3bVGARIb2MsX9sl0oRWqZ3Qleqr6u1GuQ==,iv:jPi/68hq6YBFR0qD0oU95je4GH+9Az7K5zHKrrHo0t0=,tag:D3RzqA2dDx8O3rVzDlvLpg==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:bT3FskC4ZoM=,iv:FAPKoUPRQQYIz2ceUD+vbr3TY+rLDma1IEjuU1OP0SI=,tag:g1K7vIgIQumgAR57KRZjEA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:v9tP/UpCxiE+/DL4NguaJoxZvnEBdDdw,iv:fmLCq/wV3LHZhQCj9kr8n6i8HMbAvt6RKOzeef+AOTA=,tag:zYEwUDOnrIeV6u9tXYb4hQ==,type:str]
kind: Secret
metadata:
    name: nextcloud-container-env
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeXNXd280bmFldWloWWlL
            eVFveDMremlkNVRxNWFVVzBraE8ranh4c21FCmRVU1ZqQ2hwMmRNRjlTcjJLbDAw
            eVUwMUNCK09mWmVUZG5sL09OLytoTGMKLS0tIEdxV0Y3L3h3c25HeUhEaUNZNE15
            dG1MaUlmVjZPUHZjZFhzL3dWZXhvZVkKKFRRniPgqd+koxnc4gUsVuEKLrDNgEbX
            VI6T7W+Yr+QSnbR1mXeonkKrhFnyHMLeEWlBeQK8iOdbWz9LuJsysg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T10:06:27Z"
    mac: ENC[AES256_GCM,data:5fLv6VAkP+7C4ncx2rofaiItH8AZytyeyAbhmB9iorfCz6SqtsVfv8R0xjuApDlGnGWdPkIXOwyv5qtJ8YX33soaozhTfA1OA0JBqq4MhAwxQcMAPQ89Uq68kGS2p+lU4esRmWEsd2XuZGbxPfl9P2izgdLFyQwBL/UXSwubIek=,iv:obOgqkijbIhFzji9smZvFr3nQjmNZIowHpzfaiPIhPk=,tag:W35jCVbq17YLWDo8qEmCWQ==,type:str]
    version: 3.13.3
