apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:z65LPcZsNodQyFqvBDDlj1aXKiHFEQtqSV0OsCAYqef96w==,iv:q/Yfb94NFv3uhQb9MHbTIgQfJElQvH4kG+pDjT7JiAA=,tag:DISGFCFXFzhtz8ebgOpRVw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:hF/OIOsYEfj7xHhIM5rrb57Aj94Ws2ACBngOTXNMjw==,iv:Vj/YG0jarYJSeXu/cFDC+FZizdlZ/nCCGOFmUmGM07o=,tag:hQTmGB2f4sY91QN4MXX0UA==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:Wn8HVZsIMIWrl3+LY9lQTuELqA==,iv:WGKhrSizVgXbFQawreNhmbFuxPXSUxLspHsf+q6y3Lg=,tag:r5/9GCGv82RBTCtfydLsog==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:E1En+l/n67XcTekNdIiGh2DJowazIXqOK2AFDwwrDQ==,iv:n5gSstgmeVnVJmkANlbtozZsnLGyvLHHXsbQhYgPsms=,tag:hdB5wGVKVSs9fEZ3wDG04g==,type:str]
kind: Secret
metadata:
    name: nextcloud-container-env
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MTE0RE5ycUxBZUZHcDJJ
            SlFuWGI3bTBMbCs4TDNRdzZ6WERjcXk5K1ZZCi9oSmE5R29Nak93OEowNjl1NUt1
            WHIrODhDSjlvZjNiZDBSVDk1RUFndjQKLS0tIDJSRFB0K2pGNnBYMm1velFtYm0w
            S2RkSFRRdGlPbFd2bTZUMk5ERmp0ZDAKkO3Dh9hA8W0vXfAtnZ4SoxrGo3vH1vb+
            BcYfB4zSH92qXu0YyfvKgTnni9fWT9ZFcIfiSCnZ12F140KcHwpAiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T08:07:12Z"
    mac: ENC[AES256_GCM,data:x8oxTFyct/FY/1EQuz9lB5pkpTyUE9R9kjQHe+HyE43wx3RZvjz14jVnSM6PwtoCOcOrDj9B3iaDlPwwAsTY0hdU/8ZulmA2cxAIxlLal1Jo7HJTi23fGCDOtAxdyiBOCpqQp3MSjafFSRAU9hKBSS2TMV9Y6Sb7mMnMAfsRuVk=,iv:fC3AP6xY6ta4KcF/yorTZ1TC2A8xapDeyIIlxN4I4gs=,tag:e0CNiFNJsLuL+6WhPV3izQ==,type:str]
    version: 3.13.3
