apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-container-env
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:ZgxlGxYAz6ntRyQvgn3yiubBJNmmqyDMmiuhjN4xE2CquDGylnz4aVVpkwITKKZiDqInIiTXq64/UgAMfV9w0g==,iv:zQOw7aP6Kbjnxg7ELqE+obJW6wn/8z/1S2c94jfKeu0=,tag:Dvi1YkcXoUMjrf3KRn9Q4g==,type:str]
    SIGNUPS_ALLOWED: ENC[AES256_GCM,data:bcAkfw==,iv:sGP1A9VKChAF+ymCijsodn11ee2e5ScW8XoeabF2FSI=,tag:Fm+eErtYd9ASGYD2H2wK5Q==,type:str]
    WEBSOCKET_ENABLED: ENC[AES256_GCM,data:sazKIQ==,iv:EgytFMF+LBz2PwzkP6zfFT4C3fmnYgd+vc8NPUOWZSY=,tag:lCLI83LkyuO2r159iRtVjA==,type:str]
    DOMAIN: ENC[AES256_GCM,data:7YNovEnVOGaSw8fIpDXL4GVtYgNhW/2dI2cJXw==,iv:FblFP/bz078gETfrGyjpRxZikE33gJto7bK/FZztY/4=,tag:P5KJDWZR66pleRq4tg6iiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZnF2Z2ViK3p0bFYxT0JT
            aWMxTU0xaVl6VkUzdDRNRnhLRWtHbVlvZVFzCmtFb2NsRXBMekNqbmpxUFNSeG9x
            S084cVZvV1piZ0tIdVRCNEFqY1NTU0kKLS0tIGN3VHdtQk1SeVZkTkFiR3FveEpy
            SU41VDhiRUtzREF2U081K2RNQ1N1Z0kK3quO4yLsNAV05nKhBgdX4RENhlXLa8i0
            0DYFZvRrYgNuAeNh7OY0RKjQKj8UbsD6cwSHrHYjZZYnIGafumRQBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T19:04:16Z"
    mac: ENC[AES256_GCM,data:XUnewlvQWBR3Y+06VtjViqzYUChttc9+a5ehZT3aMcMKNVHKP1FHy8saIe55lKvQsl77mj8UtftI+R30CAdskfNXdid0DV+Y73cuGWr1HwldAiRUO1TMfHndLlqJFg3N/YyKomFlUVfp7hLUG49CEIj3c2wo6pTm7uQBpLdlLYk=,iv:6raABASwxzAYZ5OY1KKH+eY43+mip9/HpwEnMwl24M4=,tag:SiDqoD/3A8Rj6r3O+vpT1w==,type:str]
    version: 3.13.3
