apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-container-env
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:ZgxlGxYAz6ntRyQvgn3yiubBJNmmqyDMmiuhjN4xE2CquDGylnz4aVVpkwITKKZiDqInIiTXq64/UgAMfV9w0g==,iv:zQOw7aP6Kbjnxg7ELqE+obJW6wn/8z/1S2c94jfKeu0=,tag:Dvi1YkcXoUMjrf3KRn9Q4g==,type:str]
    SIGNUPS_ALLOWED: ENC[AES256_GCM,data:Kzg+sjY=,iv:KNBirdygeDaQLepfQ737QbHknt2hArghoTxh0oaW+8o=,tag:58FKUcJOz2ZpFVxla3XMhw==,type:str]
    WEBSOCKET_ENABLED: ENC[AES256_GCM,data:sazKIQ==,iv:EgytFMF+LBz2PwzkP6zfFT4C3fmnYgd+vc8NPUOWZSY=,tag:lCLI83LkyuO2r159iRtVjA==,type:str]
    DOMAIN: ENC[AES256_GCM,data:7YNovEnVOGaSw8fIpDXL4GVtYgNhW/2dI2cJXw==,iv:FblFP/bz078gETfrGyjpRxZikE33gJto7bK/FZztY/4=,tag:P5KJDWZR66pleRq4tg6iiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNk1ERytMSUVsRDFvZGVn
            dVd3M3MyeUVVUGF1VENsL08vS0JCLzhpOVdJCkh5U2dpcVFwMW84L24rdUhHOFJz
            d05VdmRFMnNKMlYrbHpaZXBvTUUybWMKLS0tIHhUT1ZJaDJvN1ZyRG50cGxyWGRS
            amIra0gxVFpnb29XVXUrVTJaNy9TNGcK8zkNLsJjQI0RQf7UScc7EIVvETR24OSQ
            2D+vBUsQiRLp1zt2woLtNlTIdhzopTpalbxDTA1utitJijihUqrrfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qslrqkngwjzvh9kg0vf0ccy70fk6m68plem26225pnkklxar7p4swpchnh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T17:34:12Z"
    mac: ENC[AES256_GCM,data:hiMLBs4T0ELL8fABTOd/vtwWoJfWxtKjNs75WriTAfe509UgF1AXM74QD5CFpYDf28Nzr5q8FUv3RwgsELscbQmZTN5V8SU2Zqh+Bu/jSOkKMmqKdA9S0L1UOkMXFnY2/hodQzIoTtPGthddd2tFZuNjbFCOmEJcL2wSlpwUaXA=,iv:uHwMp6j/sQy3Wl9C5h2uq/oxOUkFWBszutqMb4pxNqo=,tag:+oVQNu0/0uQLfqTXOIQD/Q==,type:str]
    version: 3.13.3
