apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Qa0kDZV5qoE=,iv:9brBssHFEV9NR6X8ReR3Zx454OtPNacD2HcRL51tsLk=,tag:Q2UHFmyJYiP47pvvN84w+Q==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:lhqYjdgLwpc=,iv:Dkqn+Pw4xrvh0qjSLyRFYqIG0Du758qpbMb5WfajnNQ=,tag:TIjFDojGR6paMAPMTmyrJg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWGRvQkR6ZUJlZVZnU0Zx
            MUFCbElMM2hrV3BNdmtqdnl5d0tocTRXMkRnCm5MY295STEybnN1NEx6UFRmVm5o
            YVpad0VCdEdjYnF4VFQvUjZBQVhySTgKLS0tIGl3RnN4RDN0b1lJVGNmcDB6b1ZO
            QXVLTFJsV2lJMnlBWnR2N1BnVFl0bFEKHvfZU5p/t81z3ek4LzP1Uwt08/+bc7C7
            SqTIe8hk7Aj/VimQhIgdqTa+bFIYlVNHE0VZ+/dIM7CpljkrQ7wQyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qslrqkngwjzvh9kg0vf0ccy70fk6m68plem26225pnkklxar7p4swpchnh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T08:26:50Z"
    mac: ENC[AES256_GCM,data:/P6YriRF/n++2nM1cQBHOkHTzRMSvkqYu+MlN2J2WxHJi4xYkxEaPtrF5rCPk5nYokIcYP+hvzdmvHa7dbSTMz1vnKnYn7+3t+5mC24hIHZPfam6/Th4QX7FKP6tmkuH6VhnWZiXZVCLR/MJSs0a51xzEVbO0nURjv32RF+zOHc=,iv:2VBLhtZoxsNLkL3S95I2vcJtKjij6hyeVAgTKP+X334=,tag:epDlFLnVfvLuBF17LNB/5Q==,type:str]
    version: 3.13.3
