apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Qa0kDZV5qoE=,iv:9brBssHFEV9NR6X8ReR3Zx454OtPNacD2HcRL51tsLk=,tag:Q2UHFmyJYiP47pvvN84w+Q==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:lhqYjdgLwpc=,iv:Dkqn+Pw4xrvh0qjSLyRFYqIG0Du758qpbMb5WfajnNQ=,tag:TIjFDojGR6paMAPMTmyrJg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TW00Q2FRbitrSXdZQXFQ
            NXE1SzdaSURHcFpmSXdqN3c0OUtockwwZ2trCjR4VjhPMXVGTEhTVDF2dk1Ea0h0
            bkJReXZjN245MVRKb3EyQ2gwL1RVQjAKLS0tIHF2RUJROEFjSE5jL2NDeTJVRENJ
            YnFRZEx3eW1vZmhMckErM3pFUGlsbVkK06CpJwSH810xMDkyL28KcEdzzb52neoa
            DJXI6Fz2okRI18hsdMYQjMkLRgZFJo8lbxUr6A54WffFAykQlonGkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nfr8qwl3hs6nejnerd8zhchtf3j335f3tp3qct7c2zvks59yrghsy9hejk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T08:26:50Z"
    mac: ENC[AES256_GCM,data:/P6YriRF/n++2nM1cQBHOkHTzRMSvkqYu+MlN2J2WxHJi4xYkxEaPtrF5rCPk5nYokIcYP+hvzdmvHa7dbSTMz1vnKnYn7+3t+5mC24hIHZPfam6/Th4QX7FKP6tmkuH6VhnWZiXZVCLR/MJSs0a51xzEVbO0nURjv32RF+zOHc=,iv:2VBLhtZoxsNLkL3S95I2vcJtKjij6hyeVAgTKP+X334=,tag:epDlFLnVfvLuBF17LNB/5Q==,type:str]
    version: 3.13.3
