apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Homelab
    theme: dark
  services.yaml: |
    - Media:
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.tonygunnca.com
            description: Movies & TV
        - Navidrome:
            icon: navidrome.png
            href: https://navidrome.tonygunnca.com
            description: Music
    - Storage & Sync:
        - Nextcloud:
            icon: nextcloud.png
            href: https://nextcloud.tonygunnca.com
            description: Cloud Storage
    - Utilities:
        - Vaultwarden:
            icon: vaultwarden.png
            href: https://vault.tonygunnca.com
            description: Password Manager
        - Linkding:
            icon: linkding.png
            href: https://linkding.tonygunnca.com
            description: Bookmarks
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        locale: nl
        format:
          timeStyle: long
          dateStyle: long
    - openweathermap:
        label: los angeles #optional
        latitude: 34.0522
        longitude: -118.2437
        units: metric # or imperial
        provider: openweathermap
        apiKey: youropenweathermapkey # required only if not using provider, this reveals api key in requests
        cache: 5 # Time in minutes to cache API responses, to stay within limits
        format: # optional, Intl.NumberFormat options
          maximumFractionDigits: 1
    - kubernetes:
        cluster:
        # Shows cluster-wide statistics
        show: true
        # Shows the aggregate CPU stats
        cpu: true
        # Shows the aggregate memory stats
        memory: true
        # Shows a custom label
        showLabel: true
        label: "cluster"
      nodes:
        # Shows node-specific statistics
        show: true
        # Shows the CPU for each node
        cpu: true
        # Shows the memory for each node
        memory: true
        # Shows the label, which is always the node name
        showLabel: true
  bookmarks.yaml: |
    []
  kubernetes.yaml: |
    ""
  docker.yaml: |
    ""
  proxmox.yaml: |
    ""
  custom.css: ""
  custom.js: ""