apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      containers:
        - name: stirling-pdf
          image: stirlingtools/stirling-pdf:2.14.2
          ports:
            - containerPort: 8080

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: stirling-pdf-data
              mountPath: /configs
      volumes:
        - name: stirling-pdf-data
          persistentVolumeClaim:
            claimName: stirling-pdf-data-pvc